FROM node:22.14.0-alpine3.21
LABEL authors="tomer_avivi"
EXPOSE 3000
WORKDIR /app

RUN npm install -g nodemon

COPY package*.json ./
COPY tsconfig*.json ./
COPY eslint.config.ts ./
COPY scripts/build.ts ./scripts/


RUN npm install
COPY src /app/src

RUN npm run build

CMD ["npm", "run", "dev:hot"]
